/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package diseños;

import logueo.inicio;



/**
 *
 * @author ASUS
 */
public class vista_admin extends javax.swing.JFrame {

    /**
     * Creates new form vista_admin
     */
    public vista_admin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_irRegistroDoc = new javax.swing.JButton();
        btn_isistencias = new javax.swing.JButton();
        btn_docente = new javax.swing.JButton();
        btnCarreras = new javax.swing.JButton();
        btnCarreras1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 800));

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setForeground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMINISTRADOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(456, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        btn_irRegistroDoc.setBackground(new java.awt.Color(18, 90, 173));
        btn_irRegistroDoc.setFont(new java.awt.Font("Segoe UI Historic", 3, 15)); // NOI18N
        btn_irRegistroDoc.setForeground(new java.awt.Color(255, 255, 255));
        btn_irRegistroDoc.setText("Registrar Docentes");
        btn_irRegistroDoc.setBorderPainted(false);
        btn_irRegistroDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_irRegistroDocActionPerformed(evt);
            }
        });

        btn_isistencias.setBackground(new java.awt.Color(18, 90, 173));
        btn_isistencias.setFont(new java.awt.Font("Segoe UI Historic", 3, 15)); // NOI18N
        btn_isistencias.setForeground(new java.awt.Color(255, 255, 255));
        btn_isistencias.setText("Consulta de Asistencias");
        btn_isistencias.setBorderPainted(false);
        btn_isistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_isistenciasActionPerformed(evt);
            }
        });

        btn_docente.setBackground(new java.awt.Color(18, 90, 173));
        btn_docente.setFont(new java.awt.Font("Segoe UI Historic", 3, 15)); // NOI18N
        btn_docente.setForeground(new java.awt.Color(255, 255, 255));
        btn_docente.setText("Mostrar Docentes");
        btn_docente.setBorderPainted(false);
        btn_docente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_docenteActionPerformed(evt);
            }
        });

        btnCarreras.setBackground(new java.awt.Color(18, 90, 173));
        btnCarreras.setFont(new java.awt.Font("Segoe UI Historic", 3, 15)); // NOI18N
        btnCarreras.setForeground(new java.awt.Color(255, 255, 255));
        btnCarreras.setText("Mostrar Carreras");
        btnCarreras.setBorderPainted(false);
        btnCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrerasActionPerformed(evt);
            }
        });

        btnCarreras1.setBackground(new java.awt.Color(244, 208, 208));
        btnCarreras1.setFont(new java.awt.Font("Segoe UI Historic", 3, 15)); // NOI18N
        btnCarreras1.setText("Cerrar Seción");
        btnCarreras1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnCarreras1.setBorderPainted(false);
        btnCarreras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarreras1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCarreras1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_irRegistroDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_docente, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_isistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btn_irRegistroDoc)
                .addGap(57, 57, 57)
                .addComponent(btn_isistencias)
                .addGap(53, 53, 53)
                .addComponent(btn_docente)
                .addGap(51, 51, 51)
                .addComponent(btnCarreras)
                .addGap(34, 34, 34)
                .addComponent(btnCarreras1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\3° SEMESTRE\\PROYECTO-3ro\\Control_asistencia\\Control_asistencia\\src\\main\\java\\imagenes\\BEyoooooooooo.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(319, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_irRegistroDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_irRegistroDocActionPerformed
        // TODO add your handling code here:
        Registro_docentes doc=new Registro_docentes();
        doc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_irRegistroDocActionPerformed

    private void btn_isistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_isistenciasActionPerformed
        // TODO add your handling code here:
        vista_asistencia asi =new vista_asistencia();
        asi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_isistenciasActionPerformed

    private void btn_docenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_docenteActionPerformed
        // TODO add your handling code here:
        Vista_docente doce=new Vista_docente();
        doce.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_docenteActionPerformed

    private void btnCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrerasActionPerformed
        // TODO add your handling code here:
        Vista_carrera carre=new Vista_carrera();
        carre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCarrerasActionPerformed

    private void btnCarreras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarreras1ActionPerformed
        // TODO add your handling code here:
        inicio ini=new inicio();
        ini.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCarreras1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarreras;
    private javax.swing.JButton btnCarreras1;
    private javax.swing.JButton btn_docente;
    private javax.swing.JButton btn_irRegistroDoc;
    private javax.swing.JButton btn_isistencias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
